# Generated by Django 5.1.7 on 2025-03-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "Пользователь", "verbose_name_plural": "Пользователи"},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True, help_text="Загрузите изображение.", null=True, upload_to="avatar/", verbose_name="Аватар"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Необязательное поле. Введите ваш номер телефона.",
                max_length=15,
                null=True,
                verbose_name="Номер телефона",
            ),
        ),
    ]
