# Generated by Django 5.1.6 on 2025-02-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Содержимое поста")),
                ("preview", models.ImageField(blank=True, null=True, upload_to="preview/", verbose_name="Превью")),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
                ("publication_at", models.BooleanField(default=False, verbose_name="Признак публикации")),
                ("number_of_views", models.IntegerField(default=0, verbose_name="Количество просмотров")),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ["-created_at"],
            },
        ),
    ]
