# Generated by Django 5.1.7 on 2025-03-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="number_of_views",
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name="Количество просмотров"),
        ),
    ]
