# Generated by Django 5.1.6 on 2025-02-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country", models.CharField(max_length=50, verbose_name="Страна")),
                ("address", models.CharField(max_length=200, verbose_name="Адрес")),
                ("phone", models.CharField(default="+7(999)-999-99-99", max_length=15, verbose_name="Номер телефона")),
                ("email", models.EmailField(max_length=254, verbose_name="Адрес электронной почты")),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ["country"],
            },
        ),
    ]
