# Generated by Django 5.1.6 on 2025-02-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="phone",
            field=models.CharField(default="+7(999)-999-99-99", max_length=20, verbose_name="Номер телефона"),
        ),
    ]
