# Generated by Django 5.1.7 on 2025-03-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="images/", verbose_name="Изображение"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(verbose_name="Стоимость продукта"),
        ),
    ]
