# Generated by Django 5.1.7 on 2025-03-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_image_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_publication",
            field=models.BooleanField(default=False, verbose_name="Статус публикации"),
        ),
    ]
